config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :tasks 
  
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  #get 'pages/home', to: 'pages#home'
  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/task.rb
class Task < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
# <! ------------------------>
    validates :user_id, presence: true
# <! ------------------------>
    validates :due_date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tasks, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 105 },
             uniqueness: { case_sensitive: false },
             format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
    
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to tasks_path if logged_in?
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Incorrect login information"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    # https://github.com/mislav/will_paginate
    
    def index
        if params[:search]
            @tasks = Task.where("title like ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 3)
        else 
            @tasks = Task.paginate(page: params[:page], per_page: 3)
        end
    end

    def new
        @task = Task.new
    end

    def edit
    end

    def create
        @task = Task.new(task_params)
        @task.user = current_user
        if @task.save
             flash[:success] = "Task was successfully created"
             redirect_to task_path(@task)
         else
             render 'new'
        end
    end

    def update
        if @task.update(task_params)
            flash[:success] = "Task was successfully updated"
            redirect_to task_path(@task)
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @task.destroy
        flash[:danger] = "Task was successfully destroyed"
        redirect_to tasks_path
    end


    private
        def set_task
          @task = Task.find(params[:id])
        end

        def task_params
            params.require(:task).permit(:title, :description, :due_date)
        end
        

        def require_same_user
            # add ... and !current_user.admin?
          if current_user != @task.user and !current_user.admin?
            flash[:danger] = "You can only edit or delete tasks you've set"
            redirect_to root_path
          end
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    # only admin can be totally destructive ...
    before_action :require_admin, only: [:destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 3)
    end

    def new
        @user = User.new
    end
 # we know the top level key is going to be user
    def create
        @user = User.new(user_params)
        if @user.save
           session[:user_id] = @user.id
           flash[:success] = "Welcome to Task Master #{@user.username}"
           redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
        # @user = User.find(params[:id])
    end

    def update
        # @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to tasks_path
        else
            render 'edit'
        end
    end

    def show
        # @user = User.find(params[:id])
    end

     def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all tasks created by user have been deleted"
        redirect_to users_path
     end

    private
    def user_params
        params.require(:user).permit(:username,:email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
          flash[:danger] = "You can only edit your own account"
          redirect_to root_path
        end
    end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
    def due_date_from_parameters
        if params[:search].present?
            params[:search][:due_date]
        end
    end
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy <a href="https://www.ucd.ie">Where the world stops to code</a>
            by <a href="http://www.facebook.com/cuileann">Colin Sheehan</a>
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
       <a href="#" class="close" data-dismiss="alert">&#215;</a>
       <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
  <% end %>
 </div>
</div> 

app/views/layouts/_navigation.html.erb
<!--
    This navbar is adapted from the bootstrap template navigation bar: 
      https://getbootstrap.com/docs/4.0/components/navbar/#nav

-->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Tasker-Master", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Tasks", tasks_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add task <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Task", new_task_path %></li>
            </ul>
          </li>
        <% end %>

          </ul>
        </li>
      </ul>
        <!---->
      <% if current_page?(tasks_path) %>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <%= form_tag(tasks_path, method: :get, id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class:"form-control", placeholder: "search tasks" %>
            <%= button_tag(class: "btn btn-default btn-sm", type: "submit") do %>submit
            <i class="glyohicon glypyicon-search"></i>
      <% end %>  
      <% end %>  
      </div>
        </form>
      <% end %>   
      <!---->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task Master</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation'%>
  <%= render 'layouts/messages'%>

  <div class="container">
    <%= yield %>       
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>This is what it's all about</h1>

<%= link_to 'Home' , root_path %>

app/views/pages/home.html.erb
<!--<h1>Home, sweet home!</h1>-->
<div class="center jumbotron">
    <br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br>
    <div align="right">
        <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg btn-xlg"%>
    </div>
</div>

app/views/shared/_errors.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%= pluralize(obj.errors.count, "error")%>
                    prohibited this task from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/tasks/_form.html.erb
<%= render 'shared/errors', obj: @task %>
<%= javascript_include_tag "datetimepicker_initializer.js" %>


<!--
     The form below is taken from from bootstrap at 
     https://getbootstrap.com/docs/4.0/components/forms/
     
--->

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@task, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :task %>
            </div>
            <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of task", autofocus: true %>
       </div>
      </div>
       <div class="form-group">
        <div class="control-label col-sm-2">
                <%= f.label :description %> </br>
        </div>
        <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of task"%>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
                <%= f.label :due_date %> </br>
        </div>
        <div class="col-sm-8">
                <div class='input-group date' id='datetimepicker1'>
                       <%= f.text_field :due_date, class: "form-control", data: { behavior: 'datetimepicker1' } %> 
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
        </div>
     </div>  
       <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Submit task", class: 'btn btn-primary btn-lg' %>
         </div>
       </div>

        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
         [ <%= link_to "Cancel and return to task listing",tasks_path %>  ]
        </div>
    </div>
</div>

app/views/tasks/_task.html.erb
<div>
   
    <% obj.each do |task|%>
    </br>
        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="well well-lg">
            
                    <div class="task-title" >
                        <%= link_to task.title, task_path(task)%>
                    </div>
                 <% if logged_in? && (current_user == task.user || current_user.admin?) %>
                      <div class="task-actions">
                            <%= link_to "Edit", edit_task_path(task), class: "btn btn-xs btn-primary" %>
                            <%= link_to "Delete", task_path(task), method: :delete,
                                 data:{ confirm: "Are you sure?"},class: "btn btn-xs btn-danger"%>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
  
    <% end %>
 
</div>

app/views/tasks/edit.html.erb
<h1 align="center">Edit task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<div>
    <h1 align="center">Task List:</h1>
</div>

<div align="center">
  <%= will_paginate %>
</div>
 
<%= render 'task', obj: @tasks %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/tasks/new.html.erb
<%= javascript_include_tag "datetimepicker_initializer.js" %>
<h1 align="center">Create a Task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="well col-xs-8 col-xs-offset-2">
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li class="task-title">
            <%= link_to @task.user.username, user_path(@task.user) %> 
            </li>
            <small>
                
        <!--https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize-->
        
             ( <%= pluralize(@task.user.tasks.count, "task") if @task.user.tasks %> )
            </small>
          
        </div>
      </div>
    </ul>
    <h2 align="left"><%= @task.title %></h2><br>
    <h4 class="left"><strong><i>Steps</i></strong></h4>
    
    <i>  <%= simple_format(@task.description) %>  </i> 
     <div class="task-actions">
        <div class="task-meta-details">
            <small>
                <p>
                   <i>deadline on</i>  <b><%= @task.due_date.to_s[0, 10] if @task.due_date.present? %></b> <i>at</i>  <b><%= @task.due_date.to_s[10, 6] if @task.due_date.present? %></b>  |
                    <i>Time remaining... </i>   <%= distance_of_time_in_words(Time.now, @task.due_date) if @task.due_date.present?%>
                </p>
                    Created <%= time_ago_in_words(@task.created_at)%> ago | last updated: <%= time_ago_in_words(@task.updated_at)%> ago
            </small>
        </div>
       <% if logged_in? && ( current_user == @task.user || current_user.admin?) %>
          <%= link_to "Edit", edit_task_path(@task), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", task_path(@task), method: :delete, data:{ confirm: "Are you sure?"},class: "btn btn-xs btn-danger"%>
       <% end %>
        <%= link_to "View all", tasks_path, class: "btn btn-xs btn-success"%>
     </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<!--
     The form below is taken from from bootstrap at 
     https://getbootstrap.com/docs/4.0/components/forms/
     
--->
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username %>
            </div>
            <div class="col-sm-8">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
       </div>
      </div>

       <div class="form-group">
        <div class="control-label col-sm-2">
                <%= f.label :email %> </br>
        </div>
        <div class="col-sm-8">
            <%= f.email_field :email,  class: "form-control", placeholder: "Enter email"%>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
                <%= f.label :password %> </br>
        </div>
        <div class="col-sm-8">
            <%= f.password_field :password,  class: "form-control", placeholder: "Enter password"%>
        </div>
      </div>


       <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
         </div>
       </div>

        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
         [ <%= link_to "Cancel and return to task listing",tasks_path %>  ]
        </div>
    </div>
</div>

<!-------------------------------------------------------->

app/views/users/edit.html.erb
<h1 align="center"> Edit your account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Task Masters</h1>
<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
  
          <li class="task-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.tasks.count, "task") if user.tasks %></small></li>
     <!------------------------>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete,
                data: { confirm: "Are you sure you want to delete the user and all their tasks?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for TaskMaster</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"><%= @user.username %>'s Tasks </h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">

  </div>
</div>

<div align="left">
<!--------------------------->
<%= render 'tasks/task', obj: @user.tasks %>
<!--------------------------->
</div>